using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GuniKitchen.Web.Models
{
    [Table("Categories")]
    public class Category
    {

        /// <summary>
        ///     The ID of the Category
        /// </summary>
        [Display(Name = "Category ID")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public short CategoryId { get; set; }


        /// <summary>
        ///     The Name of the Category
        /// </summary>
        [Display(Name = "Category Name")]
        [Required]
        [MinLength(3, ErrorMessage = "{0} should have a minimum of {1} characters")]
        [StringLength(30, ErrorMessage = "{0} cannot have more than {1} characters in length.")]
        public string CategoryName { get; set; }

        /// <summary>
        ///     The date time stamp when the record was created.
        /// </summary>
        /// <remarks>
        ///     This is marked as a "computed" column, to inform EF that the value for this column
        ///     would be generated by the Database during an INSERT operation, 
        ///     and the developer cannot assign a value to the field.
        ///     
        ///     However, to ensure that this is handled correctly, set the default value 
        ///     in the ApplicationDbContext class during the "OnModelCreating" method.
        /// </remarks>
        [Display(Name = "Created at")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreatedAt { get; set; }



        #region Navigational Properties to the Product Model

        public ICollection<Product> Products { get; set; }

        #endregion

    }
}
